In [1]:
import tensorflow as tf
print('TensorFlow version:', tf.__version__)

2024-02-16 14:41:33.261205: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-16 14:41:38.936306: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-16 14:41:38.947301: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-16 14:41:49.498275: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


TensorFlow version: 2.13.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

In [4]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.18007657, -0.68223315,  0.10911386,  0.35477296, -0.10411231,
         0.06427316, -0.02151521, -0.24485885,  0.32929373, -0.1701917 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.08484105, 0.05134784, 0.11329215, 0.1448399 , 0.09153705,
        0.10832427, 0.09941876, 0.07951909, 0.1411961 , 0.08568384]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.2226262

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

2024-02-16 16:42:05.695590: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/5
1875/1875 [==============================] - 8s 3ms/step - loss: 0.2983 - accuracy: 0.9134
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1449 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1071 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0885 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0753 - accuracy: 0.9763


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

2024-02-16 16:44:09.902356: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 31360000 exceeds 10% of free system memory.


313/313 - 1s - loss: 0.0816 - accuracy: 0.9742 - 670ms/epoch - 2ms/step


[0.08161455392837524, 0.9742000102996826]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.03566651e-07, 5.15682963e-09, 4.75383473e-07, 7.85699085e-05,
        3.61420074e-12, 2.17461761e-07, 7.51043238e-12, 9.99918938e-01,
        3.92915211e-07, 1.05327922e-06],
       [2.86583006e-08, 1.30576279e-03, 9.98642862e-01, 5.10902937e-05,
        4.00140736e-15, 1.89233390e-07, 1.82545745e-09, 2.45555448e-13,
        1.43066771e-07, 3.23964929e-14],
       [6.19886237e-07, 9.99128640e-01, 7.58754104e-05, 1.97308455e-05,
        1.67518847e-05, 5.53542850e-06, 1.27589974e-05, 6.50121481e-04,
        8.96089769e-05, 4.59601893e-07],
       [9.99435484e-01, 4.96126562e-09, 7.35962603e-05, 3.97730537e-06,
        4.06064004e-07, 1.71300198e-05, 3.04490561e-04, 1.36791728e-04,
        3.01511149e-09, 2.82084420e-05],
       [9.58558849e-06, 1.39166135e-11, 3.23490963e-06, 2.23298997e-07,
        9.86321807e-01, 1.85764407e-07, 9.71484496e-06, 1.20450975e-04,
        9.37888785e-07, 1.35337515e-02]], dtype=float32)>